const FETCH_POSTS_DATA = 'SET_POSTS_DATA'
const FETCH_POSTS_DATA_ERROR = 'FETCH_POSTS_DATA_ERROR'
const FETCH_POSTS_DATA_SUCCESS = 'FETCH_POSTS_DATA_SUCCESS'
const ASYNC_FETCH_POSTS_DATA_SUCCESS = 'ASYNC_FETCH_POSTS_DATA_SUCCESS'

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_FAILURE';

export const PostsActionsTypes = {
    FETCH_POSTS_DATA,
    FETCH_POSTS_DATA_ERROR,
    FETCH_POSTS_DATA_SUCCESS,
    ASYNC_FETCH_POSTS_DATA_SUCCESS
}
export const CommentsActionTypes = {
    FETCH_COMMENTS_SUCCESS,
    FETCH_COMMENTS_ERROR,
    FETCH_COMMENTS_REQUEST
}

